import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ClerkProvider, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

import { JetBrains_Mono } from 'next/font/google'
import { Crown } from 'lucide-react'
import Link from 'next/link'

const jetBrainsMono = JetBrains_Mono({
    subsets: ['latin'],
    preload: true,
    variable: '--font-jetbrains',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
})

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} ${jetBrainsMono.variable} antialiased bg-[#E1E1E3]`}
                    cz-shortcut-listen="true"
                >
                    <div className="flex flex-1 justify-between items-center p-3 px-10 ">
                        <div></div>
                        <div className="flex flex-row justify-center items-center gap-3 cursor-pointer">
                            <Link href={'/'}>
                                <p className="text-4xl font-jetBrainsMono italic font-semibold">
                                    SpeedScript
                                    <span className="text-green-400">.</span>
                                </p>
                            </Link>

                            <Link href={'/leaderboard'}>
                                <p className="font-jetBrainsMono flex flex-row text-lg justify-center gap-4 bg-yellow-500 items-center p-2  rounded-full">
                                    <Crown size={22} />
                                </p>
                            </Link>
                        </div>

                        <div>
                            <SignedIn>
                                <UserButton />
                            </SignedIn>
                            <SignedOut>
                                <SignedIn />
                            </SignedOut>
                        </div>
                    </div>
                    <div className="py-10 ">{children}</div>
                </body>
            </html>
        </ClerkProvider>
    )
}
